-- MySQL Script generated by MySQL Workbench
-- 03/07/15 11:19:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema boodschappendb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema boodschappendb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boodschappendb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `boodschappendb` ;

-- -----------------------------------------------------
-- Table `boodschappendb`.`lijst`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `boodschappendb`.`lijst` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `done` TINYINT(1) NULL,
  `item` TEXT NULL,
  `winkel` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
