################################################################################
# REVERSE PROXY                                                                #
#                                                                              #
# Serves as a reverse proxy for the application                                #
################################################################################
FROM nginx
MAINTAINER Willem Meints <willem@mein-design.nl>

COPY ./nginx.conf /etc/nginx/nginx.conf

